POST https://localhost:8000/user/signup HTTP/1.1
content-type: application/json

{
    "name": "panda",
    "email": "debajyoti112@gmail.com",
    "password": "12345"
}
###
POST https://localhost:8000/user/login HTTP/1.1
content-type: application/json

{
    "email": "dpppp@gmail.com",
    "password": "12345"
}

###
POST https://localhost:8000/product HTTP/1.1
content-type: application/json

{
    "name":"pro1",
    "purches_price":200,
    "selling_price":250


}

